### ISSUE TITLE
Export type `ActionCode` and `Code`?

### ISSUE THREAD

**Issue by iredmail** [d--j/go-milter#11]
We need to log response and final action so that sysadmin can easily understand the response, hence converting Code / ActionCode to string like `accept`, `continue`, `reject` is required. But:

- they're defined in `internal/` package, we can not use them directly.
- milter package doesn't offer function / method to do such convert.

So is it better to export `Code`, `ActionCode`, `Message`, `ModifyActCode`, all `Act*`, all `Code*`? They all are most important parts of the milter protocol.

**Comment by d--j** [comment]
Hi @iredmail,

could you elaborate on how you want to do the logging/tracing that you need these types/constants? How do you get to the raw data that you actually want to use `ActionCode` and `Code`? Are you implementing a server or client? 
When implementing a client: Are you using the [mailfilter abstraction](https://pkg.go.dev/github.com/d--j/go-milter@v0.8.2/mailfilter) or are you implementing your own [Milter](https://pkg.go.dev/github.com/d--j/go-milter?utm_source=godoc#Milter)?

FYI: The [`cmd` package](https://github.com/d--j/go-milter/tree/main/cmd) has both a logging client and server. They do not need to access that low-level types to do their logging.

This library aims to abstract away all protocol specifics of the milter protocol – that's why all constants in the `wire` package are internal and that's why I am a little bit reluctant to make them part of the public interface of this library.

**Comment by iredmail** [comment]
> could you elaborate on how you want to do the logging/tracing that you need these types/constants?

I want to log the action like `accept`, `reject <reject-reason>` instead of byte `a` (SMFIR_ACCEPT), `r <reject-reason>` (SMFIR_REJECT).

> How do you get to the raw data that you actually want to use `ActionCode` and `Code`? 

I write plugins for (a custom) milter server, each plugin registers itself in different state (e.g. `Connect`, `Helo`, `EndOfMessage`) and returns `(*milter.Response, error)`. For example:

```
// it implements milter.Milter interface.
type Milter struct {
    // many fields here
}

type Plugin interface {
        Name() string
        Priority() int
        Apply(b *Milter, m *milter.Modifier) (*milter.Response, error)
}

type Registered struct {
        Connect      []Plugin
        Helo         []Plugin
        MailFrom     []Plugin
        RcptTo       []Plugin
        EndOfHeaders []Plugin
        EndOfMessage []Plugin
}

func applyPlugins(b *Milter, m *milter.Modifier, plugins []Plugin) (*milter.Response, error) {
        for _, p := range plugins {
                response, err := p.Apply(b, m)
                if err != nil {
                        // log
                        return milter.RespContinue, err
                }

                if !response.Continue() {
                        b.Logger.Info(`... response='%s' ...`, Pretty(response), )

                        return response, nil
                }
        }

        return milter.RespContinue, nil
}
```

The `Pretty()` function is what i'm working on.
When a plugin returns response like `RejectWithCodeAndReason(451, "policy rejection")`, i'd like to log something like `temp_fail 451 policy rejection`; and `RejectWithCodeAndReason(550, "blacklisted")`, i'd like to log `reject 500 blacklisted`.

> Are you implementing a server or client?

A milter server (for Postfix).

**Comment by d--j** [comment]
Hi @iredmail 

please have a look at PR #12 – does this handle your use case?

You would be able to write

```go
// Applies all plugins registered in certain state.
func applyPlugins(b *Milter, m *milter.Modifier, plugins []Plugin) (*milter.Response, error) {
        for _, p := range plugins {
                response, _ := p.Apply(b, m)
                if err != nil {
                        // omit
                }

                if !response.Continue() {
                        b.Logger.Info(`... %s ...`, response.String(), )

                        return response, nil
                }
        }

        return milter.RespContinue, nil
}
```

**Comment by iredmail** [comment]
> please have a look at PR #12 – does this handle your use case?

Yes, this is indeed what i'm looking for, but since i cannot modify imported milter library directly, i have to write my own one instead. Do you plan to merge this PR?

**Comment by d--j** [comment]
The returned string is [logfmt](https://www.brandur.org/logfmt) compatible – ading commas would not be compatible. You could use a logfmt parser like https://pkg.go.dev/github.com/go-logfmt/logfmt#example-Decoder to change the output to your liking.

I have added the `data_len` on top of the `data` since the `data` string might very well include hex codes (uint32 numbers, null-bytes, etc.) and thus you would need to parse the `data` string to figure out the actual byte length of it.

**Comment by d--j** [comment]
its released: https://github.com/d--j/go-milter/releases/tag/v0.8.3

**Comment by iredmail** [comment]
Thanks @d--j :)
